version: "3"

services:
  whoami:
    image: docker.io/containous/whoami:latest
    deploy:
      mode: replicated
      replicas: 4
      labels:
        - "traefik.frontend.rule=Host:me.skynewz.dev"
        - "traefik.enable=true"
        - "traefik.port=80"
      placement:
        constraints: [node.role == worker]
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
