version: "3.7"

services:
  whoami:
    image: docker.io/containous/whoami:latest
    deploy:
      mode: replicated
      replicas: 4
      labels:
        - "traefik.frontend.rule=Host:me.skynewz.dev"
        - "traefik.enable=true"
        - "traefik.port=80"
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
