debug = false

logLevel = "INFO"
defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]

[retry]

[api]

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "skynewz.dev"
  watch = true
  exposedByDefault = false
  network = "traefik-network"

[acme]
  email = "contact@skynewz.dev"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  acmeLogging = true
  caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" # Remove in production
  [acme.dnsChallenge]
    provider = "gandiv5"
    resolvers = ["ns-212-a.gandi.net", "1.1.1.1:53", "8.8.8.8:53"]
  [[acme.domains]]
    main = "*.skynewz.dev"
    sans = ["skynewz.dev"]
