version: "3"

services:
  portainer:
    image: portainer/portainer:1.22.0
    restart: always
    command: -H unix:///var/run/docker.sock --admin-password="$$2y$$05$$JFtRw7TKGfM9RypYigLcW.ilNyTw1WwBMyVeKPVJIuiKTKcYI2kt6"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer/data:/data
    networks:
      - traefik-network
    labels:
      - "traefik.frontend.rule=Host:portainer.skynewz.dev"
      - "traefik.port=9000"
      - "traefik.enable=true"

networks:
  traefik-network:
    external: true
