version: "3.2"

services:
  agent:
    image: docker.io/portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - traefik-network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: docker.io/portainer/portainer:1.22.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password-file /run/secrets/admin_password
    secrets:
      - admin_password
    volumes:
      - /data/portainer/data:/data:/data
    networks:
      - traefik-network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 512M
      labels:
        - "traefik.frontend.rule=Host:portainer.skynewz.dev"
        - "traefik.port=9000"
        - "traefik.enable=true"

secrets:
  admin_password:
    file: admin_password.txt

networks:
  traefik-network:
    external: true
