---
- name: Install fail2ban
  apt:
    name: fail2ban
    force_apt_get: true

- name: Install fail2ban conf file
  copy:
    src: fail2ban-jail.custom.conf
    dest: /etc/fail2ban/jail.d/custom.conf
    owner: root
    group: root
    mode: 0644

- name: Restart fail2ban daemon
  service:
    name: fail2ban
    state: restarted
