---
- name: Install python dependencies for Swarm
  pip:
    name: docker
    
- name: Join Docker swarm master
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    listen_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ hostvars['manager1']['docker_swarm_join_token']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs:
      - "{{ hostvars['manager1']['ansible_default_ipv4']['address'] }}"
